import { UserRole } from './types';
import {
  HomeIcon,
  ArchiveBoxIcon,
  DocumentTextIcon,
  UsersIcon,
  CurrencyDollarIcon,
  UserCircleIcon,
  ChartBarIcon,
  ClipboardDocumentListIcon,
  DocumentPlusIcon,
  CalendarDaysIcon,
  UserGroupIcon,
  BriefcaseIcon,
  MapIcon,
  Cog6ToothIcon,
  ArrowUpOnSquareIcon,
  ShieldCheckIcon,
  ClipboardDocumentCheckIcon,
} from '@heroicons/react/24/outline';

export const GERMAN_VAT_RATES = [19, 7, 0];

export const EXPENSE_CATEGORIES = [
  { id: 'travel', label: 'travel' },
  { id: 'office_supplies', label: 'office_supplies' },
  { id: 'entertainment', label: 'entertainment' },
  { id: 'vehicle_costs', label: 'vehicle_costs' },
  { id: 'advertising', label: 'advertising' },
  { id: 'phone_internet', label: 'phone_internet' },
  { id: 'rent', label: 'rent' },
  { id: 'other', label: 'other' },
];

// Default permissions for roles if not configured in the database
export const defaultPermissions: Record<UserRole, string[]> = {
  super_admin: ['dashboard', 'dispatcher', 'customers', 'appointments', 'visits', 'quotes', 'invoices', 'inventory', 'expenses', 'tasks', 'reports', 'team', 'settings', 'profile', 'migration-center', 'audit-log', 'text-blocks'],
  admin: ['dashboard', 'dispatcher', 'customers', 'appointments', 'visits', 'quotes', 'invoices', 'inventory', 'expenses', 'tasks', 'reports', 'team', 'settings', 'profile', 'migration-center', 'audit-log', 'text-blocks'],
  key_user: ['dashboard', 'dispatcher', 'customers', 'appointments', 'visits', 'quotes', 'invoices', 'inventory', 'expenses', 'tasks', 'reports', 'team', 'profile', 'text-blocks'],
  field_service_employee: ['dashboard', 'customers', 'appointments', 'visits', 'quotes', 'invoices', 'inventory', 'expenses', 'tasks', 'profile'],
};

export const allNavLinks = [
    { to: '/', label: 'dashboard', icon: HomeIcon, permissionKey: 'dashboard', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/dispatcher', label: 'dispatcher', icon: MapIcon, permissionKey: 'dispatcher', defaultRoles: ['super_admin', 'admin', 'key_user'] },
    { to: '/customers', label: 'customers', icon: UsersIcon, permissionKey: 'customers', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/appointments', label: 'appointments', icon: CalendarDaysIcon, permissionKey: 'appointments', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/visits', label: 'visits', icon: BriefcaseIcon, permissionKey: 'visits', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/quotes', label: 'quotes', icon: DocumentPlusIcon, permissionKey: 'quotes', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/invoices', label: 'invoices', icon: DocumentTextIcon, permissionKey: 'invoices', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/inventory', label: 'inventory', icon: ArchiveBoxIcon, permissionKey: 'inventory', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/expenses', label: 'expenses', icon: CurrencyDollarIcon, permissionKey: 'expenses', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/tasks', label: 'tasks', icon: ClipboardDocumentListIcon, permissionKey: 'tasks', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/reports', label: 'reports', icon: ChartBarIcon, permissionKey: 'reports', defaultRoles: ['super_admin', 'admin', 'key_user'] },
    { to: '/text-blocks', label: 'textBlocks', icon: ClipboardDocumentCheckIcon, permissionKey: 'text-blocks', defaultRoles: ['super_admin', 'admin', 'key_user'] },
    { to: '/audit-log', label: 'auditLog', icon: ShieldCheckIcon, permissionKey: 'audit-log', defaultRoles: ['super_admin', 'admin'] },
    { to: '/team', label: 'team', icon: UserGroupIcon, permissionKey: 'team', defaultRoles: ['super_admin', 'admin', 'key_user'] },
    { to: '/legal', label: 'legalContent', icon: ShieldCheckIcon, permissionKey: 'legal-content', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
    { to: '/settings', label: 'settings', icon: Cog6ToothIcon, permissionKey: 'settings', defaultRoles: ['super_admin', 'admin'] },
    { to: '/migration-center', label: 'migrationCenter', icon: ArrowUpOnSquareIcon, permissionKey: 'migration-center', defaultRoles: ['super_admin', 'admin'] },
    { to: '/profile', label: 'profile', icon: UserCircleIcon, permissionKey: 'profile', defaultRoles: ['super_admin', 'admin', 'key_user', 'field_service_employee'] },
];

export const translations = {
  de: {
    // Modules & Pages
    dashboard: 'Dashboard',
    inventory: 'Inventar',
    invoices: 'Rechnungen',
    customers: 'Kunden',
    expenses: 'Ausgaben',
    profile: 'Profil',
    reports: 'Berichte',
    tasks: 'Aufgaben',
    quotes: 'Angebote',
    appointments: 'Termine',
    team: 'Team',
    visits: 'Einsätze',
    dispatcher: 'Disponent',
    settings: 'Einstellungen',
    migrationCenter: 'Migrationscenter',
    emails: 'E-Mails',
    documents: 'Dokumente',
    agenda: 'Agenda',
    activity: 'Aktivität',
    activities: 'Aktivitäten',
    history: 'Verlauf',
    auditLog: 'Prüfprotokoll',
    textBlocks: 'Textbausteine',
    helpContent: 'Hilfe-Inhalte',
    legalContent: 'Rechtliches',
    agb: 'AGB',
    datenschutz: 'Datenschutz',
    dataPrivacy: 'Datenschutz-Center',

    // Common Actions & Terms
    save: 'Speichern',
    cancel: 'Abbrechen',
    actions: 'Aktionen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    deleting: 'Löschen...',
    view: 'Ansehen',
    close: 'Schließen',
    new: 'Neu',
    create: 'Erstellen',
    loading: 'Laden...',
    processing: 'Verarbeite...',
    sending: 'Senden...',
    saving: 'Speichern...',
    searching: 'Suchen...',
    search: 'Suchen...',
    all: 'Alle',
    name: 'Name',
    email: 'E-Mail',
    phone: 'Telefon',
    address: 'Adresse',
    notes: 'Notizen',
    status: 'Status',
    total: 'Gesamt',
    quantity: 'Menge',
    price: 'Preis',
    date: 'Datum',
    description: 'Beschreibung',
    organization: 'Organisation',
    upload: 'Hochladen',
    download: 'Herunterladen',
    user: 'Benutzer',
    internal: 'Intern',
    at: 'um',
    type: 'Typ',
    content: 'Inhalt',
    on: 'am',
    send: 'Senden',
    preview: 'Vorschau',
    
    // Auth & Profile
    login: 'Anmelden',
    logout: 'Abmelden',
    signUp: 'Registrieren',
    password: 'Passwort',
    welcomeBack: 'Willkommen zurück bei ZoguOne',
    createYourAccount: 'Erstellen Sie Ihr Konto',
    registrationSuccessMessage: 'Registrierung erfolgreich! Bitte überprüfen Sie Ihre E-Mails, um Ihr Konto zu verifizieren.',
    dontHaveAccount: 'Haben Sie noch kein Konto?',
    alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
    setNewPassword: 'Neues Passwort festlegen',
    newPassword: 'Neues Passwort',
    confirmNewPassword: 'Neues Passwort bestätigen',
    passwordLengthRequirement: 'Das Passwort muss mindestens 6 Zeichen lang sein.',
    passwordsDoNotMatch: 'Die Passwörter stimmen nicht überein.',
    passwordUpdatedSuccess: 'Ihr Passwort wurde erfolgreich aktualisiert!',
    redirectToLogin: 'Sie werden zur Anmeldeseite weitergeleitet...',
    updatePassword: 'Passwort aktualisieren',
    resetPassword: 'Passwort zurücksetzen',
    profile_settings: 'Profileinstellungen',
    companyInformation: 'Firmeninformationen',
    companyInformationHint: 'Diese Informationen erscheinen auf Rechnungen und Angeboten.',
    companyLogo: 'Firmenlogo',
    change: 'Ändern',
    personalInformation: 'Persönliche Informationen',
    personalInformationHint: 'Aktualisieren Sie hier Ihre persönlichen Daten.',
    emailCannotBeChanged: 'E-Mail (kann nicht geändert werden)',
    currentPlan: 'Aktueller Plan',
    full_name: 'Vollständiger Name',
    company_name: 'Firmenname',
    iban: 'IBAN',
    bic: 'BIC',
    vat_id: 'USt-IdNr.',
    forgotPassword: 'Passwort vergessen?',
    forgotPasswordTitle: 'Passwort zurücksetzen',
    forgotPasswordInstructions: 'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen Anweisungen zum Zurücksetzen Ihres Passworts.',
    requestReset: 'Zurücksetzen anfordern',
    backToLogin: 'Zurück zum Login',
    profileUpdatedSuccess: 'Profil erfolgreich aktualisiert!',
    errorUpdatingProfile: 'Fehler beim Aktualisieren des Profils:',
    noLogo: 'Kein Logo',

    // Header & Navigation
    quickCreate: 'Schnellerstellung',
    refreshData: 'Daten aktualisieren',
    toggleNotifications: 'Benachrichtigungen umschalten',
    toggleSidebar: 'Seitenleiste umschalten',
    closeAllTabs: 'Alle Tabs schließen',
    searchPlaceholder: 'Kunden, Rechnungen, Produkte suchen...',
    
    // Dashboard
    loadingDashboard: 'Dashboard wird geladen...',
    superAdminMode: 'Sie befinden sich im Super-Admin-Modus.',
    totalRevenueThisYear: 'Gesamtumsatz (dieses Jahr)',
    unpaidInvoices: 'Unbezahlte Rechnungen',
    sales_overview: 'Verkaufsübersicht',
    recent_invoices: 'Letzte Rechnungen',
    actionCenter: 'Aktionszentrum',
    overdueInvoices: 'Überfällige Rechnungen',
    quotesExpiringSoon: 'Angebote laufen bald ab',
    unassignedVisits: 'Nicht zugewiesene Einsätze',
    dispatchHub: 'Dispositions-Hub',
    goToDispatcher: 'Zum Disponenten gehen',
    unassignedActivityToday: 'nicht zugewiesene Aktivität für heute.',
    unassignedActivitiesToday: 'nicht zugewiesene Aktivitäten für heute.',
    teamLoadToday: 'Teamauslastung heute',
    noEmployeesWithActivitiesToday: 'Keine Mitarbeiter mit Aktivitäten heute.',
    noSalesDataThisYear: 'Keine Verkaufsdaten für dieses Jahr.',
    noRecentInvoices: 'Keine aktuellen Rechnungen.',
    loadingAgenda: 'Agenda wird geladen...',
    noActivitiesFound: 'Keine Aktivitäten gefunden',
    agendaClear: 'Ihre Agenda für diesen Zeitraum ist leer.',
    pending_quotes: 'Offene Angebote',
    
    // Invoices & Quotes
    newInvoice: 'Neue Rechnung',
    invoice: 'Rechnung',
    invoice_number: 'Rechnungsnr.',
    issue_date: 'Ausstellungsdatum',
    due_date: 'Fälligkeitsdatum',
    searchByInvoice: 'Suche nach Rechnungsnr. oder Kunde...',
    allStatuses: 'Alle Status',
    confirmDeleteInvoice: 'Sind Sie sicher, dass Sie diese Rechnung löschen möchten?',
    noInvoicesFound: 'Keine Rechnungen gefunden.',
    editInvoice: 'Rechnung bearbeiten',
    viewInvoice: 'Rechnung ansehen',
    downloadPDF: 'PDF herunterladen',
    copyPaymentLink: 'Zahlungslink kopieren',
    viewPaymentReceipt: 'Zahlungsbeleg ansehen',
    selectCustomer: 'Einen Kunden auswählen',
    items: 'Positionen',
    addItem: 'Position hinzufügen',
    addProduct: 'Produkt hinzufügen',
    unitPrice: 'Einzelpreis',
    vatPercent: 'MwSt. %',
    // Fix: Added missing translation keys for 'subtotal' and 'totalVAT' to align with the type definitions and prevent errors.
    subtotal: 'Zwischensumme',
    totalVAT: 'MwSt. Gesamt',
    invoiceSavedSuccess: 'Rechnung erfolgreich gespeichert!',
    quoteSavedSuccess: 'Angebot erfolgreich gespeichert!',
    pleaseSelectCustomer: 'Bitte wählen Sie einen Kunden aus.',
    newQuote: 'Neues Angebot',
    quote_number: 'Angebotsnr.',
    searchByQuote: 'Suche nach Angebotsnr. oder Kunde...',
    confirmDeleteQuote: 'Sind Sie sicher, dass Sie dieses Angebot löschen möchten?',
    noQuotesFound: 'Keine Angebote gefunden.',
    editQuote: 'Angebot bearbeiten',
    viewQuote: 'Angebot ansehen',
    valid_until: 'Gültig bis',
    convertToInvoice: 'In Rechnung umwandeln',
    confirmConvertToInvoiceMsg: 'Sind Sie sicher, dass Sie das Angebot Nr. {number} in eine Rechnung umwandeln möchten? Dies markiert das Angebot auch als "akzeptiert".',
    convert: 'Umwandeln',
    payOnline: 'Hier bezahlen',
    invoiceIsPaid: 'Diese Rechnung ist bezahlt. Änderungen sind nicht erlaubt.',
    quoteIsAccepted: 'Dieses Angebot wurde akzeptiert und kann nicht mehr bearbeitet werden.',
    quote: 'Angebot',
    
    // Customers
    newCustomer: 'Neuer Kunde',
    addNewCustomer: 'Neuen Kunden hinzufügen',
    searchByCustomer: 'Suche nach Name oder Kundennr....',
    confirmDeleteCustomer: 'Sind Sie sicher, dass Sie diesen Kunden löschen möchten?',
    noCustomersFound: 'Keine Kunden gefunden.',
    editCustomer: 'Kunde bearbeiten',
    customer_number: 'Kundennr.',
    customerDetails: 'Kundendetails',
    customer: 'Kunde',
    
    // Products & Inventory
    newProduct: 'Neues Produkt',
    editProduct: 'Produkt bearbeiten',
    searchByProduct: 'Suche nach Name oder Produktnr....',
    product_number: 'Produktnr.',
    stock: 'Lager',
    confirmDeleteProduct: 'Sind Sie sicher, dass Sie dieses Produkt löschen möchten?',
    noProductsFound: 'Keine Produkte gefunden.',
    stockManagement: 'Lagerverwaltung',
    minStockLevel: 'Mindestlagerbestand',
    expectedRestockDate: 'Erwartetes Auffülldatum',
    selling_price: 'Verkaufspreis',
    currentStockLevel: 'Aktueller Lagerbestand',
    stockLevelHint: 'Leer lassen, wenn Sie den Lagerbestand nicht verfolgen.',
    inventoryTrackingOptional: 'Lagerverfolgung (Optional)',
    inventoryTrackingHint: 'Aktivieren Sie die Lagerverfolgung, um Benachrichtigungen bei niedrigem Lagerbestand zu erhalten.',
    lowStockThreshold: 'Niedrigbestand-Schwelle',
    lowStockThresholdHint: 'Sie erhalten eine Benachrichtigung, wenn der Bestand dieses Niveau erreicht.',
    manualStatusOverride: 'Manueller Status',
    manualStatusOverrideHint: "Der Status ist meist automatisch. Wählen Sie 'Bald verfügbar', um ein Nachfülldatum festzulegen.",
    available: 'Verfügbar',
    low: 'Niedrig',
    notAvailable: 'Nicht verfügbar',
    availableSoon: 'Bald verfügbar',
    productType: 'Produkttyp',
    good: 'Ware',
    service: 'Dienstleistung',
    unit: 'Einheit',
    unitPlaceholder: 'z.B. Std, km, Stk',
    
    // Expenses
    addExpense: 'Ausgabe hinzufügen',
    editExpense: 'Ausgabe bearbeiten',
    newExpense: 'Neue Ausgabe',
    searchByExpense: 'Suche nach Beschreibung oder Nr....',
    expense_number: 'Ausgabennr.',
    amount: 'Betrag',
    category: 'Kategorie',
    confirmDeleteExpense: 'Sind Sie sicher, dass Sie diese Ausgabe löschen möchten?',
    noExpensesFound: 'Keine Ausgaben gefunden.',
    
    // Tasks
    addTask: 'Aufgabe hinzufügen',
    editTask: 'Aufgabe bearbeiten',
    showCompletedTasks: 'Erledigte Aufgaben anzeigen',
    noTasksFound: 'Keine Aufgaben gefunden.',
    markAsComplete: 'Als erledigt markieren',
    markAsIncomplete: 'Als unerledigt markieren',
    assignTo: 'Zuweisen an',
    
    // Appointments
    addAppointment: 'Termin hinzufügen',
    editAppointment: 'Termin bearbeiten',
    noAppointmentsFound: 'Keine Termine gefunden.',
    startTime: 'Startzeit',
    endTime: 'Endzeit',
    internalAppointment: 'Interner Termin',
    absence: 'Abwesenheit',
    standard: 'Standard',
    allDay: 'Ganztägig',

    // Team
    team_management: 'Team-Verwaltung',
    add_member: 'Mitglied hinzufügen',
    current_members: 'Aktuelle Teammitglieder',
    pending_members: 'Ausstehende Mitglieder',
    role: 'Rolle',
    email_address: 'E-Mail-Adresse',
    sendInvite: 'Einladung senden',
    confirmRemoveMember: 'Sind Sie sicher, dass Sie dieses Mitglied aus Ihrem Team entfernen möchten? Seine Daten bleiben erhalten, aber es verliert den Zugriff.',
    confirmCancelInvite: 'Sind Sie sicher, dass Sie diese Einladung stornieren möchten?',
    key_user: 'Hauptbenutzer',
    field_service_employee: 'Außendienstmitarbeiter',
    
    // Visits
    newVisit: 'Neuer Einsatz',
    visitDetails: 'Einsatzdetails',
    searchByVisit: 'Suche nach Einsatznr., Kunde oder Ort...',
    noVisitsFound: 'Keine Einsätze gefunden.',
    visit_number: 'Einsatznr.',
    assignedEmployee: 'Zugeordneter Mitarbeiter',
    location: 'Ort',
    purpose: 'Zweck/Notizen',
    internalVisitNotes: 'Einsatz-Anweisung',
    productsUsed: 'Verwendete Produkte',
    addProducts: 'Produkte hinzufügen',
    relatedExpenses: 'Zugehörige Ausgaben',
    addExpenses: 'Ausgaben hinzufügen',
    sendReminder: 'Erinnerung senden',
    einsatzprotokoll: 'Einsatzprotokoll',
    products_used: 'Verwendete Produkte',
    position: 'Pos.',
    expenses_related: 'Zugehörige Ausgaben',
    signature_customer: 'Unterschrift Kunde',
    visitSummaryPDF: 'Einsatzprotokoll PDF',
    sendSummary: 'Protokoll senden',
    createFollowUpInvoice: 'Folge-Rechnung erstellen',
    egCustomerAddress: 'z.B. Kundenadresse',
    noEmailsSentForVisit: 'Für diesen Einsatz wurden keine E-Mails gesendet.',
    visitCompletedAndSigned: 'Dieser Einsatz ist abgeschlossen und unterschrieben. Keine weiteren Änderungen sind erlaubt.',
    maintenance: 'Wartung',
    repair: 'Reparatur',
    consulting: 'Beratung',
    training: 'Schulung',

    // Settings
    access_control: 'Zugriffskontrolle',
    module_permissions: 'Modulberechtigungen',
    selectOrg: 'Organisation auswählen',
    selectOrgToBegin: 'Bitte wählen Sie eine Organisation aus, um zu beginnen.',
    integrations: 'Integrationen',
    premiumFeatures: 'Premium-Funktionen',
    stripePaymentGateway: 'Stripe Zahlungs-Gateway',
    stripeDescription: 'Ermöglichen Sie Kunden, Rechnungen direkt online zu bezahlen. Zahlungen werden über Stripe abgewickelt und auf Ihr verbundenes Bankkonto eingezahlt.',
    stripeConnected: 'Stripe ist erfolgreich verbunden!',
    stripeAccountId: 'Konto-ID',
    connectWithStripe: 'Mit Stripe verbinden',
    connecting: 'Verbinden...',
    datevAccountSetup: 'DATEV-Kontoeinrichtung',
    datevAccountDescription: 'Geben Sie die von Ihrem Steuerberater bereitgestellten Kontonummern ein. Diese sind für korrekte Finanzdatenexporte erforderlich.',
    debtorAccount: 'Sammeldebitorenkonto',
    creditorAccount: 'Sammelkreditorenkonto',
    revenueAccountMapping: 'Erlöskontenzuordnung',
    revenue19: 'Erlöskonto 19% MwSt.',
    revenue7: 'Erlöskonto 7% MwSt.',
    revenue0: 'Erlöskonto 0% MwSt.',
    expenseAccountMapping: 'Aufwandskontenzuordnung',
    expenseAccountDescription: 'Ordnen Sie Ihre Ausgabenkategorien den DATEV-Aufwandskonten zu.',
    premiumVisitReminders: 'Einsatz-Erinnerungen',
    premiumVisitRemindersDesc: 'Erlauben Sie dieser Organisation, automatische E-Mail-Erinnerungen für anstehende Einsätze zu senden.',
    premiumEmailSending: 'E-Mail-Versand',
    premiumEmailSendingDesc: 'Erlauben Sie dieser Organisation, Dokumente (Rechnungen, Angebote) per E-Mail zu versenden.',
    premiumDatevExport: 'DATEV-Export',
    premiumDatevExportDesc: 'Erlauben Sie dieser Organisation, Finanzdaten für DATEV zu exportieren.',
    premiumPaymentGateway: 'Zahlungs-Gateway',
    premiumPaymentGatewayDesc: 'Erlauben Sie dieser Organisation, sich mit Stripe zu verbinden und Rechnungszahlungen zu akzeptieren.',
    premiumDocumentStorage: 'Kundendokumentenspeicher',
    premiumDocumentStorageDesc: 'Erlauben Sie Benutzern in dieser Organisation, Dateien an Kunden anzuhängen.',
    premiumTextBlocks: 'Textbausteine',
    premiumTextBlocksDesc: 'Ermöglicht die Erstellung und Verwendung vordefinierter Textblöcke in Dokumenten.',
    
    // Reports
    generateReport: 'Bericht erstellen',
    generating: 'Erstelle...',
    export: 'Exportieren',
    exportForDatev: 'Für DATEV exportieren',
    exportAsCsv: 'Als CSV exportieren',
    exportAsPdf: 'Als PDF exportieren',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    newCustomers: 'Neue Kunden',
    avgInvoiceValue: 'Ø Rechnungswert',
    quoteConversion: 'Angebotskonversion',
    profitLoss: 'Gewinn & Verlust',
    totalRevenue: 'Gesamtumsatz',
    totalExpenses: 'Gesamtausgaben',
    netProfit: 'Nettogewinn',
    taxSummary: 'Steuerübersicht',
    vatCollected: 'Eingenommene MwSt.',
    vatPaidNotTracked: 'Gezahlte MwSt. aus Ausgaben wird noch nicht erfasst.',
    salesByCustomer: 'Umsatz nach Kunde',
    topSellingProducts: 'Meistverkaufte Produkte',
    teamPerformance: 'Teamleistung',
    product: 'Produkt',
    revenue: 'Umsatz',
    employee: 'Mitarbeiter',
    visitsDone: 'Erledigte Einsätze',
    noSalesDataForPeriod: 'Keine Verkaufsdaten für diesen Zeitraum.',
    noProductSalesData: 'Keine Produktverkaufsdaten.',
    noTeamPerformanceData: 'Keine Teamleistungsdaten.',
    pleaseGenerateReportFirst: 'Bitte erstellen Sie zuerst einen Bericht.',
    page: 'Seite',
    period: 'Zeitraum',
    keyPerformanceIndicators: 'Wichtige Leistungsindikatoren',
    topSalesByCustomer: 'Top-Umsatz nach Kunde',
    businessReport: 'Geschäftsbericht',
    totalSales: 'Gesamtverkäufe',
    
    // Modals & Notifications
    confirm: 'Bestätigen',
    notifications: 'Benachrichtigungen',
    markAllAsRead: 'Alle als gelesen markieren',
    clearAll: 'Alle löschen',
    noNotifications: 'Sie haben keine Benachrichtigungen.',
    confirmClearAllNotifications: 'Sind Sie sicher, dass Sie alle Benachrichtigungen löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    whatToCreate: 'Was möchten Sie erstellen?',
    selectExpenses: 'Ausgaben auswählen',
    searchExpenses: 'Ausgaben suchen...',
    addSelected: 'Ausgewählte hinzufügen',
    noResultsFor: 'Keine Ergebnisse für "{term}" gefunden.',
    selectItemToPreview: 'Wählen Sie ein Element aus, um eine Vorschau des Inhalts anzuzeigen.',
    
    // Statuses
    draft: 'Entwurf',
    sent: 'Gesendet',
    paid: 'Bezahlt',
    overdue: 'Überfällig',
    accepted: 'Akzeptiert',
    declined: 'Abgelehnt',
    planned: 'Geplant',
    completed: 'Abgeschlossen',
    cancelled: 'Abgesagt',
    pending: 'Ausstehend',
    open: 'Offen',
    in_progress: 'In Arbeit',
    done: 'Erledigt',
    expired: 'Abgelaufen',
    update: 'Aktualisieren',

    // Calendar & Dates
    day: 'Tag',
    week: 'Woche',
    month: 'Monat',
    today: 'Heute',
    
    // Misc
    title: 'Titel',
    back: 'Zurück',
    allEmployees: 'Alle Mitarbeiter',
    filterByEmployee: 'Nach Mitarbeiter filtern',
    configurationRequired: 'Konfiguration erforderlich',
    welcomeToZogu: 'Willkommen bei ZOGU Solutions! Um zu starten, verbinden Sie bitte die Anwendung mit Ihrem Supabase-Backend.',
    openFollowingFile: '1. Öffnen Sie die folgende Datei in Ihrem Code-Editor:',
    replacePlaceholders: '2. Ersetzen Sie die Platzhalterwerte mit Ihrer Supabase URL und Ihrem Anon Key. Sie finden diese in Ihren Supabase-Projekteinstellungen unter "API".',
    pageWillReload: 'Nachdem Sie die Datei gespeichert haben, sollte die Anwendung automatisch neu laden. Wenn nicht, aktualisieren Sie bitte diese Seite.',
    upgradeToPro: 'Auf Pro upgraden, um fortzusetzen',
    upgradeNow: 'Jetzt upgraden',
    emailHistory: 'E-Mail-Verlauf',
    noEmailsSent: 'Für dieses Dokument wurden keine E-Mails gesendet.',
    customerNotes: 'Kundennotizen',
    internalNotes: 'Interne Notiz',
    customerNotesHint: 'Diese Notizen sind für den Kunden sichtbar.',
    internalNotesHint: 'Diese Notizen sind nur für den internen Gebrauch.',
    noCustomer: 'Kein Kunde',
    createdBy: 'Erstellt von',
    createdAt: 'Erstellt am',
    sentBy: 'Gesendet von',
    system: 'System',
    receivesVisitReminders: 'Erhält Einsatz-Erinnerungen',
    noVisitReminders: 'Keine Einsatz-Erinnerungen',
    addImportantNotes: 'Wichtige Notizen hinzufügen...',
    noNotes: 'Keine Notizen.',
    saveNotes: 'Notizen speichern',
    noDocumentsUploaded: 'Keine Dokumente hochgeladen.',
    sendViaEmail: 'Per E-Mail senden',
    sentViaEmail: 'Per E-Mail gesendet',
    confirmSendEmailTitle: 'E-Mail senden bestätigen',
    confirmSendEmailMessage: 'Sind Sie sicher, dass Sie dieses Dokument an {email} senden möchten?',
    
    // Expense Categories
    travel: 'Reisekosten',
    office_supplies: 'Bürobedarf',
    entertainment: 'Bewirtungskosten',
    vehicle_costs: 'Fahrzeugkosten',
    advertising: 'Werbung',
    phone_internet: 'Telefon/Internet',
    rent: 'Miete',
    other: 'Sonstiges',

    // Migration Center
    importCustomers: 'Kunden importieren',
    importProducts: 'Produkte importieren',
    downloadTemplate: 'Vorlage herunterladen',
    fileRequirements: 'Datei-Anforderungen',
    mustBeCsv: 'Muss eine .csv-Datei sein.',
    headersMustMatch: 'Die Spaltenüberschriften müssen der Vorlage entsprechen:',
    uploadCsvFile: 'CSV-Datei hochladen',
    selectFile: 'Datei auswählen',
    processingFile: 'Datei wird verarbeitet...',
    uploadSuccess: 'Hochladen erfolgreich!',
    importedRows: 'Zeilen importiert.',
    failedRows: 'Zeilen fehlgeschlagen.',
    seeConsole: 'Details in der Konsole ansehen.',
    migrationWarning: 'Achtung: Bei großen Dateien kann der Upload-Vorgang mehrere Minuten dauern, da jede Zeile einzeln nummeriert wird. Bitte haben Sie Geduld und navigieren Sie nicht von dieser Seite weg.',
    
    // Signature Feature
    proofOfCompletion: 'Abschlussnachweis',
    customerSignature: 'Kundenunterschrift',
    noSignatureCaptured: 'Keine Unterschrift für diesen Einsatz erfasst.',
    getSignature: 'Unterschrift einholen',
    clear: 'Löschen',
    provideSignatureFirst: 'Bitte geben Sie zuerst eine Unterschrift an.',

    // Tooltips
    copy: 'Kopieren',
    copyInvoice: 'Rechnung kopieren',
    copyQuote: 'Angebot kopieren',
    copyProduct: 'Produkt kopieren',
    copyExpense: 'Ausgabe kopieren',
    copyTask: 'Aufgabe kopieren',
    copyVisit: 'Einsatz kopieren',
    sendEmail: 'Per E-Mail senden',
    editView: 'Bearbeiten / Ansehen',

    // Notifications
    lowStockWarning: 'Bestands-Warnung',
    stockForIsLow: 'Der Bestand für "{productName}" ist niedrig.',
    newVisitAssigned: 'Neuer Einsatz zugewiesen',
    youveBeenAssignedVisitBy: 'Ihnen wurde Einsatz #{visitNumber} von {userName} zugewiesen.',
    newTaskAssigned: 'Neue Aufgabe zugewiesen',
    taskWasAssignedToYouBy: 'Aufgabe "{taskTitle}" wurde Ihnen von {userName} zugewiesen.',
    taskUpdated: 'Aufgabe aktualisiert',
    taskWasUpdatedBy: 'Aufgabe "{taskTitle}" wurde von {userName} aktualisiert.',
    newAppointmentAssigned: 'Neuer Termin zugewiesen',
    appointmentWasAssignedToYouBy: 'Termin "{appointmentTitle}" wurde Ihnen von {userName} zugewiesen.',

    // Audit Log
    userEmail: 'Benutzer E-Mail',
    allActions: 'Alle Aktionen',
    allObjects: 'Alle Objekte',
    recordId: 'Eintrags-ID',
    object: 'Objekt',
    changes: 'Änderungen',
    empty: 'leer',
    set: 'gesetzt',
    to: 'zu',
    from: 'von',
    changed: 'Geändert',
    was: 'war',
    createdThisRecord: 'hat diesen Eintrag erstellt',
    updatedThisRecord: 'hat diesen Eintrag aktualisiert',
    deletedThisRecord: 'hat diesen Eintrag gelöscht',
    recordCreatedWithDefaults: 'Eintrag mit Standardwerten erstellt.',
    recordUpdatedNoChanges: 'Eintrag aktualisiert ohne Feldänderungen.',
    recordDeleted: 'Eintrag gelöscht.',
    recordCreatedTitle: 'Eintrag erstellt:',
    recordDeletedTitle: 'Eintrag gelöscht:',
    loadingHistory: 'Verlauf wird geladen...',
    noHistoryFound: 'Kein Verlauf für diesen Eintrag gefunden.',

    // Text Blocks
    newTextBlock: 'Neuer Textbaustein',
    editTextBlock: 'Textbaustein bearbeiten',
    noTextBlocks: 'Keine Textbausteine definiert.',
    textBlockTitle: 'Titel des Textbausteins',
    textBlockContent: 'Inhalt',
    applicableTo: 'Anwendbar für',
    placeholders: 'Platzhalter',
    availablePlaceholders: 'Verfügbare Platzhalter',
    insertTextBlock: 'Textbaustein einfügen',
    selectTextBlock: 'Textbaustein auswählen',
    confirmDeleteTextBlock: 'Sind Sie sicher, dass Sie diesen Textbaustein löschen möchten?',
    
    // Data Privacy / DSGVO
    exportDataJson: 'Daten exportieren (JSON)',
    exportAsExcel: 'Als Excel (CSV) exportieren',
    deleteData: 'Kunde & Daten löschen',
    confirmCustomerDeletionTitle: 'Kundenlöschung bestätigen',
    confirmCustomerDeletionMessage: 'Diese Aktion ist unumkehrbar und löscht den Kunden sowie alle zugehörigen Rechnungen, Angebote, Einsätze und andere Daten dauerhaft. Geben Sie zur Bestätigung die Kundennummer <strong>{customerNumber}</strong> ein.',
    dataExportedSuccessfully: 'Daten erfolgreich exportiert.',
    customerDeletedSuccessfully: 'Kunde und alle zugehörigen Daten erfolgreich gelöscht.',
    searchByNameOrId: 'Suche nach Name oder ID...',
  },
  al: {
    // Modules & Pages
    dashboard: 'Paneli',
    inventory: 'Inventari',
    invoices: 'Faturat',
    customers: 'Klientët',
    expenses: 'Shpenzimet',
    profile: 'Profili',
    reports: 'Raportet',
    tasks: 'Detyrat',
    quotes: 'Ofertat',
    appointments: 'Terminet',
    team: 'Ekipi',
    visits: 'Vizitat',
    dispatcher: 'Disponenti',
    settings: 'Cilësimet',
    migrationCenter: 'Qendra e Migrimit',
    emails: 'Emailet',
    documents: 'Dokumentet',
    agenda: 'Axhenda',
    activity: 'Aktivitet',
    activities: 'Aktivitete',
    history: 'Historia',
    auditLog: 'Regjistri i Auditimit',
    textBlocks: 'Blloqe Teksti',
    helpContent: 'Përmbajtja e Ndihmës',
    legalContent: 'Ligjore',
    agb: 'Kushtet dhe Rregullat',
    datenschutz: 'Politika e Privatësisë',
    dataPrivacy: 'Privatësia e të Dhënave',

    // Common Actions & Terms
    save: 'Ruaj',
    cancel: 'Anulo',
    actions: 'Veprimet',
    edit: 'Redakto',
    delete: 'Fshij',
    deleting: 'Duke fshirë...',
    view: 'Shiko',
    close: 'Mbyll',
    new: 'E re',
    create: 'Krijo',
    loading: 'Duke ngarkuar...',
    processing: 'Duke procesuar...',
    sending: 'Duke dërguar...',
    saving: 'Duke ruajtur...',
    searching: 'Duke kërkuar...',
    search: 'Kërko...',
    all: 'Të gjitha',
    name: 'Emri',
    email: 'Email',
    phone: 'Telefoni',
    address: 'Adresa',
    notes: 'Shënime',
    status: 'Statusi',
    total: 'Totali',
    quantity: 'Sasia',
    price: 'Çmimi',
    date: 'Data',
    description: 'Përshkrimi',
    organization: 'Organizata',
    upload: 'Ngarko',
    download: 'Shkarko',
    user: 'Përdorues',
    internal: 'Intern',
    at: 'në orën',
    type: 'Lloji',
    content: 'Përmbajtja',
    on: 'më',
    send: 'Dërgo',
    preview: 'Shikim paraprak',
    
    // Auth & Profile
    login: 'Hyr',
    logout: 'Dil',
    signUp: 'Regjistrohu',
    password: 'Fjalëkalimi',
    welcomeBack: 'Mirë se vini përsëri në ZoguOne',
    createYourAccount: 'Krijo llogarinë tënde',
    registrationSuccessMessage: 'Regjistrimi i suksesshëm! Ju lutemi kontrolloni emailin tuaj për të verifikuar llogarinë.',
    dontHaveAccount: 'Nuk keni llogari?',
    alreadyHaveAccount: 'Keni tashmë një llogari?',
    setNewPassword: 'Vendos një fjalëkalim të ri',
    newPassword: 'Fjalëkalim i ri',
    confirmNewPassword: 'Konfirmo fjalëkalimin e ri',
    passwordLengthRequirement: 'Fjalëkalimi duhet të jetë të paktën 6 karaktere i gjatë.',
    passwordsDoNotMatch: 'Fjalëkalimet nuk përputhen.',
    passwordUpdatedSuccess: 'Fjalëkalimi juaj u përditësua me sukses!',
    redirectToLogin: 'Duke ju ridrejtuar në faqen e hyrjes...',
    updatePassword: 'Përditëso fjalëkalimin',
    resetPassword: 'Rivendos Fjalëkalimin',
    profile_settings: 'Cilësimet e Profilit',
    companyInformation: 'Informacioni i Kompanisë',
    companyInformationHint: 'Ky informacion do të shfaqet në fatura dhe oferta.',
    companyLogo: 'Logo e Kompanisé',
    change: 'Ndrysho',
    personalInformation: 'Informacioni Personal',
    personalInformationHint: 'Përditësoni detajet tuaja personale këtu.',
    emailCannotBeChanged: 'Email (nuk mund të ndryshohet)',
    currentPlan: 'Plani aktual',
    full_name: 'Emri i plotë',
    company_name: 'Emri i Kompanisë',
    iban: 'IBAN',
    bic: 'BIC',
    vat_id: 'ID e TVSH-së',
    forgotPassword: 'Harruat fjalëkalimin?',
    forgotPasswordTitle: 'Rivendos fjalëkalimin',
    forgotPasswordInstructions: 'Futni emailin tuaj dhe ne do t\'ju dërgojmë udhëzime për të rivendosur fjalëkalimin tuaj.',
    requestReset: 'Kërko rivendosje',
    backToLogin: 'Kthehu te hyrja',
    profileUpdatedSuccess: 'Profili u përditësua me sukses!',
    errorUpdatingProfile: 'Gabim gjatë përditësimit të profilit:',
    noLogo: 'Pa Logo',

    // Header & Navigation
    quickCreate: 'Krijim i shpejtë',
    refreshData: 'Rifresko të dhënat',
    toggleNotifications: 'Shfaq njoftimet',
    toggleSidebar: 'Shfaq menynë anësore',
    closeAllTabs: 'Mbyll të gjitha skedat',
    searchPlaceholder: 'Kërko klientë, fatura, produkte...',
    
    // Dashboard
    loadingDashboard: 'Paneli po ngarkohet...',
    superAdminMode: 'Jeni në modalitetin Super Admin.',
    totalRevenueThisYear: 'Të ardhurat totale (këtë vit)',
    unpaidInvoices: 'Faturat e papaguara',
    sales_overview: 'Pasqyra e shitjeve',
    recent_invoices: 'Faturat e fundit',
    actionCenter: 'Qendra e Veprimit',
    overdueInvoices: 'Faturat e vonuara',
    quotesExpiringSoon: 'Ofertat që skadojnë së shpejti',
    unassignedVisits: 'Vizitat e pacaktuara',
    dispatchHub: 'Qendra e Dispozicionit',
    goToDispatcher: 'Shko te Disponenti',
    unassignedActivityToday: 'aktivitet i pacaktuar për sot.',
    unassignedActivitiesToday: 'aktivitete të pacaktuara për sot.',
    teamLoadToday: 'Ngarkesa e ekipit sot',
    noEmployeesWithActivitiesToday: 'Asnjë punonjës me aktivitete sot.',
    noSalesDataThisYear: 'Nuk ka të dhëna shitjesh për këtë vit.',
    noRecentInvoices: 'Nuk ka fatura të fundit.',
    loadingAgenda: 'Duke ngarkuar axhendën...',
    noActivitiesFound: 'Nuk u gjetën aktivitete',
    agendaClear: 'Axhenda juaj për këtë periudhë është e zbrazët.',
    pending_quotes: 'Ofertat në pritje',

    // Invoices & Quotes
    newInvoice: 'Faturë e re',
    invoice: 'Faturë',
    invoice_number: 'Nr. i faturës',
    issue_date: 'Data e lëshimit',
    due_date: 'Data e duhur',
    searchByInvoice: 'Kërko sipas nr. fature ose klienti...',
    allStatuses: 'Të gjitha statuset',
    confirmDeleteInvoice: 'Jeni i sigurt që doni ta fshini këtë faturë?',
    noInvoicesFound: 'Nuk u gjetën fatura.',
    editInvoice: 'Redakto faturën',
    viewInvoice: 'Shiko Faturën',
    downloadPDF: 'Shkarko PDF',
    copyPaymentLink: 'Kopjo linkun e pagesës',
    viewPaymentReceipt: 'Shiko Faturën e Pagesës',
    selectCustomer: 'Zgjidh një klient',
    items: 'Artikujt',
    addItem: 'Shto artikull',
    addProduct: 'Shto produkt',
    unitPrice: 'Çmimi për njësi',
    vatPercent: 'TVSH %',
    subtotal: 'Nëntotali',
    totalVAT: 'TVSH totale',
    invoiceSavedSuccess: 'Fatura u ruajt me sukses!',
    quoteSavedSuccess: 'Oferta u ruajt me sukses!',
    pleaseSelectCustomer: 'Ju lutemi zgjidhni një klient.',
    newQuote: 'Ofertë e re',
    searchByQuote: 'Kërko sipas nr. oferte ose klienti...',
    confirmDeleteQuote: 'Jeni i sigurt që doni ta fshini këtë ofertë?',
    noQuotesFound: 'Nuk u gjetën oferta.',
    editQuote: 'Redakto ofertën',
    viewQuote: 'Shiko ofertën',
    valid_until: 'E vlefshme deri më',
    convertToInvoice: 'Shndërro në faturë',
    confirmConvertToInvoiceMsg: 'Jeni i sigurt që doni ta shndërroni Ofertën #{number} në një faturë? Kjo gjithashtu do ta shënojë ofertën si "pranuar".',
    convert: 'Shndërro',
    payOnline: 'Paguaj Tani',
    invoiceIsPaid: 'Kjo faturë është paguar. Ndryshimet nuk lejohen.',
    quoteIsAccepted: 'Kjo ofertë është pranuar dhe nuk mund të redaktohet më.',
    quote: 'Ofertë',

    // Customers
    newCustomer: 'Klient i Ri',
    addNewCustomer: 'Shto klient të ri',
    searchByCustomer: 'Kërko sipas emrit ose nr. klienti...',
    confirmDeleteCustomer: 'Jeni i sigurt që doni ta fshini këtë klient?',
    noCustomersFound: 'Nuk u gjetën klientë.',
    editCustomer: 'Redakto klientin',
    customerDetails: 'Detajet e Klientit',
    customer: 'Klient',
    customer_number: 'Nr. i klientit',
    
    // Products & Inventory
    newProduct: 'Produkt i Ri',
    editProduct: 'Redakto produktin',
    searchByProduct: 'Kërko sipas emrit ose nr. produkti...',
    product_number: 'Nr. i produktit',
    stock: 'Stoku',
    confirmDeleteProduct: 'Jeni i sigurt që doni ta fshini këtë produkt?',
    noProductsFound: 'Nuk u gjetën produkte.',
    stockManagement: 'Menaxhimi i Stokut',
    minStockLevel: 'Niveli Minimal i Stokut',
    expectedRestockDate: 'Data e Pritshme e Rimbushjes',
    selling_price: 'Çmimi i shitjes',
    currentStockLevel: 'Gjendja aktuale e stokut',
    stockLevelHint: 'Lëreni bosh nëse nuk e ndiqni stokun për këtë artikull.',
    inventoryTrackingOptional: 'Ndjekja e Inventarit (Opsionale)',
    inventoryTrackingHint: 'Aktivizoni ndjekjen e stokut për të marrë njoftime për stok të ulët.',
    lowStockThreshold: 'Pragu i Stokut të Ulët',
    lowStockThresholdHint: 'Do të merrni një njoftim kur stoku të arrijë këtë nivel.',
    manualStatusOverride: 'Statusi Manual',
    manualStatusOverrideHint: "Statusi është zakonisht automatik. Zgjidhni 'Së shpejti i disponueshëm' për të vendosur një datë rimbushjeje.",
    available: 'I disponueshëm',
    low: 'I ulët',
    notAvailable: 'I padisponueshëm',
    availableSoon: 'Së shpejti i disponueshëm',
    productType: 'Lloji i Produktit',
    good: 'Mall',
    service: 'Shërbim',
    unit: 'Njësia',
    unitPlaceholder: 'p.sh. orë, km, copë',
    
    // Expenses
    addExpense: 'Shto Shpenzim',
    editExpense: 'Redakto Shpenzimin',
    newExpense: 'Shpenzim i Ri',
    searchByExpense: 'Kërko sipas përshkrimit ose nr....',
    expense_number: 'Nr. i shpenzimit',
    amount: 'Shuma',
    confirmDeleteExpense: 'Jeni i sigurt që doni ta fshini këtë shpenzim?',
    noExpensesFound: 'Nuk u gjetën shpenzime.',
    
    // Tasks
    addTask: 'Shto Detyrë',
    editTask: 'Redakto Detyrën',
    showCompletedTasks: 'Shfaq detyrat e përfunduara',
    noTasksFound: 'Nuk u gjetën detyra.',
    markAsComplete: 'Shëno si të përfunduar',
    markAsIncomplete: 'Shëno si të papërfunduar',
    assignTo: 'Cakto te',
    
    // Appointments
    addAppointment: 'Shto Termin',
    editAppointment: 'Redakto Termin',
    noAppointmentsFound: 'Nuk u gjetën termine.',
    startTime: 'Koha e fillimit',
    endTime: 'Koha e mbarimit',
    internalAppointment: 'Takim i Brendshëm',
    absence: 'Mungesë',
    standard: 'Standard',
    allDay: 'Gjithë ditën',

    // Team
    team_management: 'Menaxhimi i Ekipit',
    add_member: 'Shto Anëtar',
    current_members: 'Anëtarët Aktualë',
    pending_members: 'Anëtarët në Pritje',
    role: 'Roli',
    email_address: 'Adresa e Email-it',
    sendInvite: 'Dërgo ftesë',
    confirmRemoveMember: 'Jeni i sigurt që doni ta largoni këtë anëtar nga ekipi juaj? Të dhënat e tij do të ruhen, por ai do të humbasë qasjen.',
    confirmCancelInvite: 'Jeni i sigurt që doni ta anuloni këtë ftesë?',
    key_user: 'Përdorues kyç',
    field_service_employee: 'Punonjës i shërbimit në terren',
    
    // Visits
    newVisit: 'Vizitë e Re',
    visitDetails: 'Detajet e Vizitës',
    searchByVisit: 'Kërko sipas nr. vizite, klienti ose vendndodhjes...',
    noVisitsFound: 'Nuk u gjetën vizita.',
    visit_number: 'Nr. i vizitës',
    assignedEmployee: 'Punonjësi i caktuar',
    location: 'Vendndodhja',
    purpose: 'Qëllimi/Shënime',
    internalVisitNotes: 'Udhëzim Pune',
    productsUsed: 'Produktet e Përdorura',
    addProducts: 'Shto Produkte',
    relatedExpenses: 'Shpenzimet Përkatëse',
    addExpenses: 'Shto Shpenzime',
    sendReminder: 'Dërgo Njoftim',
    einsatzprotokoll: 'Protokolli i Vizitës',
    products_used: 'Produktet e Përdorura',
    position: 'Poz.',
    expenses_related: 'Shpenzimet Përkatëse',
    signature_customer: 'Nënshkrimi i Klientit',
    visitSummaryPDF: 'Protokolli PDF',
    sendSummary: 'Dërgo Protokollin',
    createFollowUpInvoice: 'Krijo Faturë Pasuese',
    egCustomerAddress: 'p.sh. Adresa e Klientit',
    noEmailsSentForVisit: 'Asnjë email nuk është dërguar për këtë vizitë.',
    visitCompletedAndSigned: 'Kjo vizitë është përfunduar dhe nënshkruar. Ndryshime të mëtejshme nuk lejohen.',
    maintenance: 'Mirëmbajtje',
    repair: 'Riparim',
    consulting: 'Këshillim',
    training: 'Trajnim',
    
    // Settings
    access_control: 'Kontrolli i Qasjes',
    module_permissions: 'Lejet e Moduleve',
    selectOrg: 'Zgjidh Organizatën',
    selectOrgToBegin: 'Ju lutemi zgjidhni një organizatë për të filluar.',
    integrations: 'Integrimet',
    premiumFeatures: 'Veçoritë Premium',
    stripePaymentGateway: 'Gateway Pagesash Stripe',
    stripeDescription: 'Lejoni klientët të paguajnë faturat direkt online. Pagesat procesohen nga Stripe dhe depozitohen në llogarinë tuaj bankare të lidhur.',
    stripeConnected: 'Stripe u lidh me sukses!',
    stripeAccountId: 'ID e Llogarisë',
    connectWithStripe: 'Lidhu me Stripe',
    connecting: 'Duke u lidhur...',
    datevAccountSetup: 'Konfigurimi i Llogarisë DATEV',
    datevAccountDescription: 'Futni numrat e llogarive të dhëna nga kontabilisti juaj. Këto janë të nevojshme për eksporte të sakta të të dhënave financiare.',
    debtorAccount: 'Llogaria e Debitorëve',
    creditorAccount: 'Llogaria e Kreditorëve',
    revenueAccountMapping: 'Mapimi i Llogarive të të Ardhurave',
    revenue19: 'Llogaria e të Ardhurave 19% TVSH',
    revenue7: 'Llogaria e të Ardhurave 7% TVSH',
    revenue0: 'Llogaria e të Ardhurave 0% TVSH',
    expenseAccountMapping: 'Mapimi i Llogarive të Shpenzimeve',
    expenseAccountDescription: 'Maponi kategoritë tuaja të shpenzimeve me llogaritë e shpenzimeve të DATEV.',
    premiumVisitReminders: 'Njoftimet për Vizita',
    premiumVisitRemindersDesc: 'Lejoni këtë organizatë të dërgojë njoftime automatike me email për vizitat e ardhshme.',
    premiumEmailSending: 'Dërgimi i Email-it',
    premiumEmailSendingDesc: 'Lejoni këtë organizatë të dërgojë dokumente (fatura, oferta) me email.',
    premiumDatevExport: 'Eksporti DATEV',
    premiumDatevExportDesc: 'Lejoni këtë organizatë të eksportojë të dhëna financiare për DATEV.',
    premiumPaymentGateway: 'Gateway Pagesash',
    premiumPaymentGatewayDesc: 'Lejoni këtë organizatë të lidhet me Stripe dhe të pranojë pagesa faturash.',
    premiumDocumentStorage: 'Ruajtja e Dokumenteve të Klientit',
    premiumDocumentStorageDesc: 'Lejoni përdoruesit në këtë organizatë të bashkëngjisin skedarë te klientët.',
    premiumTextBlocks: 'Blloqe Teksti',
    premiumTextBlocksDesc: 'Lejon krijimin dhe përdorimin e blloqeve të tekstit të paracaktuara në dokumente.',
    
    // Reports
    generateReport: 'Gjenero Raport',
    generating: 'Duke gjeneruar...',
    export: 'Eksporto',
    exportForDatev: 'Eksporto për DATEV',
    exportAsCsv: 'Eksporto si CSV',
    exportAsPdf: 'Eksporto si PDF',
    startDate: 'Data e Fillimit',
    endDate: 'Data e Mbarimit',
    newCustomers: 'Klientë të Rinj',
    avgInvoiceValue: 'Vlera Mesatare e Faturës',
    quoteConversion: 'Konvertimi i Ofertave',
    profitLoss: 'Fitimi & Humbja',
    totalRevenue: 'Të Ardhurat Totale',
    totalExpenses: 'Shpenzimet Totale',
    netProfit: 'Fitimi Neto',
    taxSummary: 'Përmbledhja e Taksave',
    vatCollected: 'TVSH e Mbledhur',
    vatPaidNotTracked: 'TVSH-ja e paguar nga shpenzimet nuk është gjurmuar ende.',
    salesByCustomer: 'Shitjet sipas Klientit',
    topSellingProducts: 'Produktet më të Shiturat',
    teamPerformance: 'Performanca e Ekipit',
    product: 'Produkti',
    revenue: 'Të Ardhurat',
    employee: 'Punonjësi',
    visitsDone: 'Vizitat e Kryera',
    noSalesDataForPeriod: 'Nuk ka të dhëna shitjesh për këtë periudhë.',
    noProductSalesData: 'Nuk ka të dhëna për shitjet e produkteve.',
    noTeamPerformanceData: 'Nuk ka të dhëna për performancën e ekipit.',
    pleaseGenerateReportFirst: 'Ju lutemi gjeneroni një raport së pari.',
    page: 'Faqja',
    period: 'Periudha',
    keyPerformanceIndicators: 'Treguesit Kryesorë të Performancës',
    topSalesByCustomer: 'Shitjet Kryesore sipas Klientit',
    businessReport: 'Raporti i Biznesit',
    totalSales: 'Shitjet Totale',

    // Modals & Notifications
    confirm: 'Konfirmo',
    notifications: 'Njoftimet',
    markAllAsRead: 'Shëno të gjitha si të lexuara',
    clearAll: 'Fshij të gjitha',
    noNotifications: 'Nuk keni njoftime.',
    confirmClearAllNotifications: 'Jeni i sigurt që doni të fshini të gjitha njoftimet? Ky veprim nuk mund të kthehet mbrapsht.',
    whatToCreate: 'Çfarë dëshironi të krijoni?',
    selectExpenses: 'Zgjidh Shpenzimet',
    searchExpenses: 'Kërko shpenzime...',
    addSelected: 'Shto të zgjedhurat',
    noResultsFor: 'Nuk u gjetën rezultate për "{term}".',
    selectItemToPreview: 'Zgjidhni një artikull për të parë përmbajtjen.',
    
    // Statuses
    declined: 'Refuzuar',
    expired: 'Skaduar',
    update: 'Përditëso',
    
    // Misc
    back: 'Kthehu',
    emailHistory: 'Historiku i Emaileve',
    noEmailsSent: 'Asnjë email nuk është dërguar për këtë dokument.',
    customerNotes: 'Shënime për Klientin',
    internalNotes: 'Shënim Intern',
    customerNotesHint: 'Këto shënime janë të dukshme për klientin.',
    internalNotesHint: 'Këto shënime janë vetëm për përdorim të brendshëm.',
    noCustomer: 'Pa Klient',
    createdBy: 'Krijuar nga',
    createdAt: 'Krijuar më',
    sentBy: 'Dërguar nga',
    system: 'Sistemi',
    receivesVisitReminders: 'Merr njoftime për vizita',
    noVisitReminders: 'Asnjë njoftim për vizita',
    addImportantNotes: 'Shto shënime të rëndësishme...',
    noNotes: 'Asnjë shënim.',
    saveNotes: 'Ruaj shënimet',
    noDocumentsUploaded: 'Asnjë dokument i ngarkuar.',
    sendViaEmail: 'Dërgo me Email',
    sentViaEmail: 'Dërguar me Email',
    confirmSendEmailTitle: 'Konfirmo Dërgimin e Emailit',
    confirmSendEmailMessage: 'Jeni i sigurt që doni ta dërgoni këtë dokument te {email}?',
    
    // Configuration
    configurationRequired: 'Kërkohet Konfigurim',
    welcomeToZogu: 'Mirë se vini në ZOGU Solutions! Për të filluar, ju lutemi lidhni aplikacionin me backend-in tuaj Supabase.',
    openFollowingFile: '1. Hapni skedarin e mëposhtëm në editorin tuaj të kodit:',
    replacePlaceholders: '2. Zëvendësoni vlerat e vendosura me URL-në tuaj Supabase dhe Çelësin Anon. Mund t\'i gjeni këto në Cilësimet e Projektit tuaj Supabase nën "API".',
    pageWillReload: 'Pasi të ruani skedarin, aplikacioni duhet të ringarkohet automatikisht. Nëse jo, ju lutemi rifreskoni këtë faqe.',
    upgradeToPro: 'Kaloni në Pro për të vazhduar',
    upgradeNow: 'Kalo tani',
    
    // Migration Center
    migrationWarning: 'Paralajmërim: Për skedarë të mëdhenj, procesi i ngarkimit mund të zgjasë disa minuta pasi çdo rresht numërohet individualisht. Ju lutemi kini durim dhe mos u largoni nga kjo faqe.',
    
    // Signature Feature
    proofOfCompletion: 'Dëshmi e Përfundimit',
    customerSignature: 'Nënshkrimi i Klientit',
    noSignatureCaptured: 'Asnjë nënshkrim i regjistruar për këtë vizitë.',
    getSignature: 'Merr Nënshkrimin',
    clear: 'Pastro',
    provideSignatureFirst: 'Ju lutemi jepni një nënshkrim së pari.',

    // Tooltips
    copy: 'Kopjo',
    copyInvoice: 'Kopjo faturën',
    copyQuote: 'Kopjo ofertën',
    copyProduct: 'Kopjo produktin',
    copyExpense: 'Kopjo shpenzimin',
    copyTask: 'Kopjo detyrën',
    copyVisit: 'Kopjo vizitën',
    sendEmail: 'Dërgo me Email',
    editView: 'Redakto / Shiko',

    // Notifications
    lowStockWarning: 'Paralajmërim për Stok të Ulët',
    stockForIsLow: 'Stoku për "{productName}" është i ulët.',
    newVisitAssigned: 'Vizitë e Re e Caktuar',
    youveBeenAssignedVisitBy: 'Ju është caktuar vizita #{visitNumber} nga {userName}.',
    newTaskAssigned: 'Detyrë e Re e Caktuar',
    taskWasAssignedToYouBy: 'Detyra "{taskTitle}" ju është caktuar nga {userName}.',
    taskUpdated: 'Detyra u Përditësua',
    taskWasUpdatedBy: 'Detyra "{taskTitle}" u përditësua nga {userName}.',
    newAppointmentAssigned: 'Termin i Ri i Caktuar',
    appointmentWasAssignedToYouBy: 'Termini "{appointmentTitle}" ju është caktuar nga {userName}.',

    // Audit Log
    userEmail: 'Email i Përdoruesit',
    allActions: 'Të gjitha Veprimet',
    allObjects: 'Të gjitha Objektet',
    recordId: 'ID e Regjistrimit',
    object: 'Objekti',
    changes: 'Ndryshimet',
    empty: 'bosh',
    set: 'vendosur',
    to: 'në',
    from: 'prej',
    changed: 'Ndryshuar',
    was: 'ishte',
    createdThisRecord: 'krijoi këtë regjistrim',
    updatedThisRecord: 'përditësoi këtë regjistrim',
    deletedThisRecord: 'fshiu këtë regjistrim',
    recordCreatedWithDefaults: 'Regjistrimi u krijua me vlera standarde.',
    recordUpdatedNoChanges: 'Regjistrimi u përditësua pa ndryshime në fusha.',
    recordDeleted: 'Regjistrimi u fshi.',
    recordCreatedTitle: 'Regjistrimi i krijuar:',
    recordDeletedTitle: 'Regjistrimi i fshirë:',
    loadingHistory: 'Duke ngarkuar historinë...',
    noHistoryFound: 'Nuk u gjet histori për këtë regjistrim.',
    
    // Text Blocks
    newTextBlock: 'Bllok Teksti i Ri',
    editTextBlock: 'Redakto Bllokun e Tekstit',
    noTextBlocks: 'Asnjë bllok teksti i definuar.',
    textBlockTitle: 'Titulli i Bllokut të Tekstit',
    textBlockContent: 'Përmbajtja',
    applicableTo: 'E aplikueshme për',
    placeholders: 'Placeholder-at',
    availablePlaceholders: 'Placeholder-at e disponueshëm',
    insertTextBlock: 'Fut Bllok Teksti',
    selectTextBlock: 'Zgjidh Bllokun e Tekstit',
    confirmDeleteTextBlock: 'Jeni i sigurt që doni ta fshini këtë bllok teksti?',
    
    // Data Privacy / DSGVO
    exportDataJson: 'Eksporto të Dhënat (JSON)',
    exportAsExcel: 'Eksporto si Excel (CSV)',
    deleteData: 'Fshij Klientin & të Dhënat',
    confirmCustomerDeletionTitle: 'Konfirmo Fshirjen e Klientit',
    confirmCustomerDeletionMessage: 'Ky veprim është i pakthyeshëm dhe do të fshijë përgjithmonë klientin dhe të gjitha faturat, ofertat, vizitat dhe të dhënat e tjera të lidhura. Për të konfirmuar, shkruani numrin e klientit <strong>{customerNumber}</strong>.',
    dataExportedSuccessfully: 'Të dhënat u eksportuan me sukses.',
    customerDeletedSuccessfully: 'Klienti dhe të gjitha të dhënat e lidhura u fshinë me sukses.',
    searchByNameOrId: 'Kërko sipas emrit ose ID...',
  },
};